# Uncomment the next line to define a global platform for your project
 platform :ios, '14.4'

target 'fitnessApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for charts
  pod 'Charts'
  pod 'TinyConstraints'
  pod 'GTMAppAuth'
  pod 'AppAuth'

  # Pods for Google Sign In API
  pod 'GoogleSignIn'

  target 'fitnessAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fitnessAppUITests' do
    # Pods for testing
  end

end
